### ISSUE TITLE
Why there is no content in pi-forall/version1/test/Lec1.pi?

### ISSUE THREAD

**Issue by qdwang** [sweirich/pi-forall#15]
The Lec1.pi in version1 is just the namespace, is it the same as Lec1.pi in version2?

**Comment by sweirich** [comment]
These files were part of a summer school lecture series with interactive content. The version1 copy of the repo includes deliberate holes in the development, and the first lecture was spent filling in Lec1.pi.  The final result of that lecture is in version2 (including Lec1.pi).
