### ISSUE TITLE
doc: Footnote weirdness

### ISSUE THREAD

**Issue by atsuzaki** [sweirich/pi-forall#25]
I noticed some footnote weirdness in the rendered .pdf.

The following footnote
```
\footnote{Note that
  this rule makes our language inconsistent as a logic, as it can encode
  Girard's paradox.}
```
got cut up and rendered on two different pages:

<img width="650" alt="image" src="https://github.com/sweirich/pi-forall/assets/16256974/f4170f45-a9c4-47bb-88a9-fcb217f4553a">
<img width="696" alt="image" src="https://github.com/sweirich/pi-forall/assets/16256974/5695a988-dbfa-4d85-a19d-2ec22541abbd">

**Comment by sweirich** [comment]
Thanks! I've fixed in commit 59c1626ae392b735ff1962ff929227f54cad3b75
